### ISSUE TITLE
When we edit EAD metadata using the form, if we fill the Final Date, the template loads it as the Initial date

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#427] opened 2016-07-21 09:12 UTC
Since ISO 8601 does not express uncertain or unknown dates per se, we recommend normalizing uncertain dates as approximate dates.

# How to do it? 

Use this strategy:

## Both dates exits:

`<unitdate label="UnitDates" type="inclusive" certainty="True/True" normal="1880-01-01/1990-01-01">1880-01-01/1990-01-01</unitdate>
`

## Only final date exists:

`<unitdate label="UnitDateFinal" type="inclusive" certainty="True" normal="1990-01-01">1990-01-01</unitdate>
`

## Only initial date exists:

`<unitdate label="UnitDateInitial" type="inclusive" certainty="True" normal="1880-01-01">1880-01-01</unitdate>`

**Comment by sleroux-keep** [comment] 2016-08-17 09:49
Done for EAD-2002.

**Comment by jmaferreira** [comment] 2016-09-06 11:05
I haven't tested it.

**Comment by luis100** [comment] 2016-09-06 13:27
@jmaferreira please test it before closing the issue. Deployment on staging server will be ready today.

**Comment by jmaferreira** [comment] 2016-09-06 13:46
We'll do...

**Comment by jmaferreira** [comment] 2016-09-07 15:13
Issue still stands. Replicate as:

1. fill the initial and final date
2. Edit again, erase initial date anda save
3. The initial date continues to be filled in.

**Comment by sleroux-keep** [comment] 2016-09-09 13:58
The problem is related to the date picker (#518).

**Comment by jmaferreira** [comment] 2016-10-04 11:13
On EAD-2002-DGLAB:
- None of the dates is being saved... on 

On EADC-DGLAB:
- The issue described in this issue still stands.

Check the templates. The problem might be there.

**Comment by sleroux-keep** [comment] 2016-10-10 08:57
EAD-2002 -> Fixed (initial and final dates were only processed if descriptive date was not empty...)

EAD-C -> The unitdate element doesn't allow the "label" attribute... So, if only the "final date" is filled, the XML only have ```<unitdate normal="2000-01-01"></unitdate>```

When editing again, there is no way to know that the date in the XML is the final date... So the final date is displayed in the initial date field...

**Comment by luis100** [comment] 2016-10-11 16:40
checked.

**Closed by luis100** 2016-10-11 16:40 UTC
Labels: bug
