### ISSUE TITLE
Transferred resource upload creates temp. files and does not remove them in the end

### ISSUE THREAD

**Issue by luis100** [keeps/roda#625] opened 2016-10-18 12:37 UTC
To replicate, upload a file then look for it on the Apache Tomcat temporary directory.

In the tested case, several instances of uploaded files (that were let to finish upload) were found on the temp. directory:

```
root@ea997ef67540:/usr/local/tomcat# du -hs temp/*
300M    temp/MIME2774574303056113615.tmp
4.1G    temp/MIME371485897697962364.tmp
4.1G    temp/MIME4793732065922240997.tmp
4.1G    temp/MIME8490185126325949520.tmp
1.3M    temp/index2893822617912363826
0   temp/safeToDelete.tmp
```

**Comment by jmaferreira** [comment] 2016-10-18 13:04
http://stackoverflow.com/questions/31138727/jersey-service-file-upload-causes-outofmemoryerror

**Comment by luis100** [comment] 2016-10-19 16:10
More tests reveal that the temporary file is removed when the file upload is done without any interruptions (like re-indexes). Also, it is removed when failures occur, even when disk becomes full. So it is not clear under which conditions the temporary files are actually left behind, as in the case shown above.

**Comment by hsilva-keep** [comment] 2016-10-21 15:31
First, the obvious: houston, we have a problem. Second, this problem has already been detected and registered in project's bug tracker system:
- https://java.net/jira/browse/JERSEY-2987
- https://java.net/jira/browse/MIMEPULL-13
Third, the solution: to be found.

**Comment by luis100** [comment] 2016-11-16 11:29
Guess we'll have to wait for the dependencies to fix these problem.
Moving this issue to be reviewed on a later milestone.

**Comment by nunovieira220** [comment] 2016-12-12 17:28
Note that the creation of a temporary file is still happening and only when the file is bigger than 4MB.

**Comment by hsilva-keep** [comment] 2017-05-23 13:50
Just updating links as java.net has been closed and projects relocated to github:
- https://github.com/jersey/jersey/issues/3259
- https://github.com/javaee/metro-mimepull/issues/13

**Comment by luis100** [comment] 2017-08-14 10:24
Related issues are still open, to review status in a couple of months.

**Comment by hsilva-keep** [comment] 2017-12-13 09:08
Just a quick update: I've seen some activity in related issues, but no solutions was presented so far. We'll keep waiting.

**Comment by luis100** [comment] 2018-05-24 13:10
@hsilva-keep please review the state.

**Comment by hsilva-keep** [comment] 2018-06-06 13:53
Well...The thing is...Even if the two previously mentioned issues are still open, I've tested RODA version 2.2.8 (docker container) uploading a 4GB file & the problem is no longer there. 

I've consulted jersey code & indeed the evidences show that a cleanup method exists that tries to delete the temporary file explicitly: https://github.com/jersey/jersey/blob/12e5d8bdf22bcd2676a1032ed69473cf2bbc48c7/media/multipart/src/main/java/org/glassfish/jersey/media/multipart/BodyPartEntity.java#L95

After all said, I'm closing this issue now.

**Closed by hsilva-keep** 2018-06-06 13:53 UTC
Labels: enhancement
