### ISSUE TITLE
File not characterized risk assessment plugin false positive

### ISSUE THREAD

**Issue by luis100** [keeps/roda#749] opened 2016-12-19 17:23 UTC
Ran the plugin with the format designation version checked and the result said it found a version when none existed.

![job-params](https://cloud.githubusercontent.com/assets/631728/21322172/cd81ea30-c60f-11e6-894e-35915d48ee2a.png)

![result](https://cloud.githubusercontent.com/assets/631728/21322185/d24dfe0a-c60f-11e6-80ae-7d6247e15643.png)

![details](https://cloud.githubusercontent.com/assets/631728/21322188/d5ec0188-c60f-11e6-9c29-a41906da873f.png)

**Comment by jmaferreira** [comment] 2017-01-06 10:13
The problem is with the version:

"said it found a **version** when none existed."

**Comment by rui-castro** [comment] 2017-01-06 11:27
@jmaferreira @luis100 ok. The version is probably set, but not being shown in the interface. Do an API query to the File and check the result JSON.

**Comment by luis100** [comment] 2017-01-06 11:29
@rui-castro there is no version, also tiff is known for its version not being identifiable.

**Comment by rui-castro** [comment] 2017-01-06 15:24
@luis100 fixed in PR #762

**Comment by hsilva-keep** [comment] 2017-01-25 16:01
Code from PR #762 merged and issue solved.

**Closed by hsilva-keep** 2017-01-25 16:01 UTC
Labels: bug, to review
