### ISSUE TITLE
When we try to remove a dissemination of DBVTK it outputs an error

### ISSUE THREAD

**Issue by jmaferreira** [keeps/roda#840] opened 2017-03-19 15:28 UTC
![screen shot 2017-03-19 at 15 27 28](https://cloud.githubusercontent.com/assets/3181302/24082149/9cc9127a-0cb8-11e7-9c49-c663a1c05f4b.png)
![screen shot 2017-03-19 at 15 27 25](https://cloud.githubusercontent.com/assets/3181302/24082150/9ceae5d0-0cb8-11e7-9e0b-56e92e24d69b.png)

**Comment by chalkos** [comment] 2017-03-19 16:12
HTTP 401 means unauthorized. So it seems DBVTK is denying RODA's authentication credentials.

@hsilva-keep Please check the configurations on the demo server to see if this part:

```
# Credentials provided to DBVTK to delete the DIP
dip.dbptk.credentials.username: admin
dip.dbptk.credentials.password: roda
```

is correctly configured in roda-core.properties. [source](https://github.com/keeps/roda-dbptk-plugin/wiki/Setting-it-up)

**Comment by jmaferreira** [comment] 2017-03-19 16:35
Those are not the credentials of admin in my instance.

**Comment by jmaferreira** [comment] 2017-03-19 16:41
Ok. I fixed the configuration file manually. But please find a clever way to handle this. Having admin passwords on a plain text file is a no go.

**Comment by chalkos** [comment] 2017-03-19 20:16
We discussed having user (not necessarily admin's) passwords on the viewer configuration and ended up removing them. In the RODA configuration this methodology was accepted due to lack of better options.

These credentials do not need to be the admin's. A user can be created that has permissions to delete DIPs, and that user's credentials will suffice for the integration to work.

**Comment by jmaferreira** [comment] 2017-03-20 10:09
Just to let you know.. after fixing the password on the config.. the action of removing the DIP stop issuing the 401 error, however.. it did not remove the DB from the viewer.

**Comment by luis100** [comment] 2017-04-04 16:22
@jmaferreira @chalkos what is the status of this issue?

**Comment by jmaferreira** [comment] 2017-04-05 08:11
Bruno?

**Comment by chalkos** [comment] 2017-04-05 09:00
Not fixed. At least I did not fix it.

**Comment by luis100** [comment] 2017-04-05 13:25
IMHO, the problem now seems to be that after an error has occurred while deleting a DIP the system becomes unstable, giving rise to the problem now detected by @jmaferreira 

This needs to be solved soon (milestone ends in two days and this is the only remaining issue) or marked as wontfix and closed.

@chalkos please analyse what the problem now is so we can make a decision.

**Comment by chalkos** [comment] 2017-04-07 13:29
Fixed. The problem was caused by some changes in RODA that affected the DIP creation in the plugin (DIP empty constructor used to generate an UUID and now it stopped doing that, and as such UUID was always empty, resulting in a series of 404 and 500 server errors).

**Closed by chalkos** 2017-04-07 13:29 UTC
Labels: bug
