### ISSUE TITLE
Opening login form focuses on Login button

### ISSUE THREAD

**Issue by luis100** [keeps/roda#1237] opened 2018-05-24 09:53 UTC
When opening the login form the focus gets lost into the Login button on the menu. This makes it hard to select the login textboxes.

**Comment by chalkos** [comment] 2018-06-21 11:28
The loss of focus is caused by the mouse focusing the login button.

If you click the login button and immediately move the mouse away (or don't move the mouse at all), the username text field will be focused and will not be unfocused.

If you move the mouse over the login button (even if the mouse is already there and you are just moving it somewhere else) when the login page is already loaded, the login button will be focused and the username text field will loose focus.

I'll need to analyse this further to understand if there is a way to not loose focus on the text field.

**Closed** 2022-12-13 15:35 UTC
Labels: bug
