### ISSUE TITLE
Error on ingest update after moving

### ISSUE THREAD

**Issue by luis100** [keeps/roda#656] opened 2016-10-26 16:58 UTC
When ingesting a empty SIP (touch test.zip), the following error occurred when move after auto-accept is enabled:

```
2016-10-26 16:05:02,341 [WorkersSystem-akka.actor.default-dispatcher-22] ERROR o.r.c.p.o.akka.AkkaWorkerActor - Error executing plugin.execute()
java.lang.NullPointerException: null
        at org.roda.core.plugins.plugins.PluginHelper.updateReportsAfterMovingSIPs(PluginHelper.java:756)
        at org.roda.core.plugins.plugins.PluginHelper.moveSIPs(PluginHelper.java:735)
        at org.roda.core.plugins.plugins.ingest.DefaultIngestPlugin.execute(DefaultIngestPlugin.java:255)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.handlePluginExecuteIsReady(AkkaWorkerActor.java:49)
        at org.roda.core.plugins.orchestrate.akka.AkkaWorkerActor.onReceive(AkkaWorkerActor.java:35)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by hsilva-keep** [comment] 2016-10-26 17:47
@luis100 Cannot reproduce. Will assume that this is related to a particular SIP2AIP plugin, as I wasn't able to reproduce with EARKSIPToAIPPlugin & TransferredResourceToAIPPlugin.

Nevertheless, the NPE should not occur and that can be improved.

**Comment by hsilva-keep** [comment] 2016-10-27 09:24
Improved since 7d923af52d535952f406d06c2b8cd8b9863f3883.

**Closed by hsilva-keep** 2016-10-27 09:24 UTC
Labels: bug
